default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: news_parser_dev

test:
  <<: *default
  database: news_parser_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
